// =============================================================================
// File        : volterra_top_tb.v
// Description : Self-checking testbench for volterra_top.v
//
//   * FSM-driven stimulus — all sequential logic in clocked always blocks.
//   * No #-delays anywhere except the single clock generator.
//   * rst_n driven by one initial block only (no multiple drivers).
//   * All temporary variables declared at module level (no local regs inside
//     procedural blocks — compatible with Verilog-2001 and Vivado sim).
//   * Catches 1-cycle done pulses via latches before the FSM polls them.
//   * Compares every env22 and env23 pixel against MATLAB-generated reference.
//   * Prints per-stage timing, first failing pixel, max error, final verdict.
//
// .mem files required (generated by gen_tb_vectors.m at the bottom of this file):
//   rf_input.mem   - 229376 words x 8 hex chars  (Q2.30, RF sample-major order)
//   ref_env22.mem  - 124544 words x 8 hex chars  (Q2.30 expected quad envelope)
//   ref_env23.mem  - 124544 words x 8 hex chars  (Q2.30 expected cubic envelope)
//
// Vivado: Add all *.v/*.sv source files + this file; set volterra_top_tb as
//         simulation top.  All .mem files must be in the simulation sources dir.
// =============================================================================

`timescale 1ns / 1ps

module volterra_top_tb;

// =============================================================================
// 1.  PARAMETERS  (must match volterra_top.v exactly)
// =============================================================================
localparam DW           = 32;
localparam NUM_CH       = 128;
localparam L_SAMP       = 1792;
localparam NUM_AXIAL    = 973;
localparam NUM_LAT      = 128;
localparam FIR_TAPS     = 136;
localparam M_VOLT       = 15;
localparam N_QUAD       = 120;
localparam N_CUBIC      = 680;
localparam ACCUM_W      = 64;

// Derived sizes
localparam RF_WORDS     = L_SAMP * NUM_CH;        // 229 376
localparam N_PIXELS     = NUM_AXIAL * NUM_LAT;    // 124 544

// Testbench timing
localparam CLK_HALF     = 5;        // 5 ns half-period -> 100 MHz
localparam RESET_CYCLES = 20;       // Cycles rst_n is held low
localparam POST_RST_CYC = 5;        // Idle cycles after reset de-assert
localparam SETTLE_CYC   = 8;        // Cycles to wait after w3_done

// Timeout: 250M cycles = 2.5 s @ 100 MHz (generous, covers W1+W2+W3 worst case)
localparam integer WATCHDOG_LIM = 250_000_000;

// Absolute tolerance in Q2.30 LSBs:  5000 / 2^30 ~= 4.7e-6 of full scale
localparam [DW-1:0] TOLERANCE = 32'd5_000;

// =============================================================================
// 2.  DUT PORT SIGNALS
// =============================================================================
reg          clk;
reg          rst_n;

reg  [7:0]   data_in;
reg          data_valid;
reg          start;

wire         pipeline_busy;
wire         w1_done;
wire         w2_done;
wire         w3_done;

reg          out_rd_en;
reg  [16:0]  out_rd_addr;     // max 124 543 = 17'h1E63F -> fits in 17 bits
wire [DW-1:0] env22_out;
wire [DW-1:0] env23_out;

reg  [17:0]  mf_rd_addr;      // unused in main test; kept for port completeness
wire [DW-1:0] mf_x1_out;
wire [DW-1:0] mf_x2_out;

// =============================================================================
// 3.  TEST-VECTOR MEMORIES
// =============================================================================
// rf_input  [sample_idx * NUM_CH + ch_idx]         (row-major)
// ref_env22 [ax_idx    * NUM_LAT + lat_idx]
// ref_env23 [ax_idx    * NUM_LAT + lat_idx]
reg [DW-1:0] rf_input  [0 : RF_WORDS - 1];
reg [DW-1:0] ref_env22 [0 : N_PIXELS - 1];
reg [DW-1:0] ref_env23 [0 : N_PIXELS - 1];

// =============================================================================
// 4.  FSM STATE ENCODING
// =============================================================================
localparam [3:0]
    TB_RESET        = 4'd0,
    TB_POST_RST     = 4'd1,
    TB_PULSE_START  = 4'd2,
    TB_STREAM       = 4'd3,
    TB_WAIT_W1      = 4'd4,
    TB_WAIT_W2      = 4'd5,
    TB_WAIT_W3      = 4'd6,
    TB_SETTLE       = 4'd7,
    TB_ADDR_PIX     = 4'd8,
    TB_SAMPLE_PIX   = 4'd9,
    TB_CHECK_PIX    = 4'd10,
    TB_REPORT       = 4'd11,
    TB_DONE         = 4'd12;

// =============================================================================
// 5.  STATE & DATAPATH REGISTERS
// =============================================================================
reg  [3:0]   tb_state;

// RF streaming counters
reg  [17:0]  word_idx;     // Current RF word being sent (0 .. RF_WORDS-1)
reg  [1:0]   byte_sel;     // Current byte in word: 3=MSB -> 0=LSB

// Readback pipeline
reg  [16:0]  pix_rd;       // Pixel address driven to DUT this cycle
reg  [16:0]  pix_chk;      // Pixel address whose output is checked this cycle
reg  [DW-1:0] cap_env22;   // env22_out registered one cycle after addr driven
reg  [DW-1:0] cap_env23;   // env23_out registered one cycle after addr driven

// Temporaries for TB_CHECK_PIX
// (declared at module level -- local reg inside always block is not Verilog-2001)
reg  [DW-1:0] diff22;
reg  [DW-1:0] diff23;

// Statistics
reg  [31:0]  pass22, fail22;
reg  [31:0]  pass23, fail23;
reg  [DW-1:0] max_err22, max_err23;
reg  [31:0]  ff22_ax, ff22_lat;   // First failing pixel (env22): ax, lat
reg  [31:0]  ff23_ax, ff23_lat;   // First failing pixel (env23): ax, lat
reg          ff22_logged;          // Have we printed the first env22 failure?
reg          ff23_logged;          // Have we printed the first env23 failure?

// Milestone cycle stamps
reg  [31:0]  cyc_stream_start;
reg  [31:0]  cyc_w1;
reg  [31:0]  cyc_w2;
reg  [31:0]  cyc_w3;

// Misc counters
reg  [4:0]   post_rst_cnt;
reg  [3:0]   settle_cnt;
reg  [31:0]  cycle_cnt;

// Done-pulse latches (each captures a 1-cycle pulse from the DUT)
reg          w1_lat, w2_lat, w3_lat;

// =============================================================================
// 6.  DUT INSTANTIATION
// =============================================================================
volterra_top #(
    .DATA_WIDTH  (DW),
    .NUM_CH      (NUM_CH),
    .L           (L_SAMP),
    .NUM_AXIAL   (NUM_AXIAL),
    .NUM_LATERAL (NUM_LAT),
    .TAPS        (FIR_TAPS),
    .M_VOLTERRA  (M_VOLT),
    .NTERMS_QUAD (N_QUAD),
    .NTERMS_CUBIC(N_CUBIC),
    .ACCUM_WIDTH (ACCUM_W)
) dut (
    .clk          (clk),
    .rst_n        (rst_n),
    .data_in      (data_in),
    .data_valid   (data_valid),
    .start        (start),
    .pipeline_busy(pipeline_busy),
    .w1_done      (w1_done),
    .w2_done      (w2_done),
    .w3_done      (w3_done),
    .out_rd_en    (out_rd_en),
    .out_rd_addr  (out_rd_addr),
    .env22_out    (env22_out),
    .env23_out    (env23_out),
    .mf_rd_addr   (mf_rd_addr),
    .mf_x1_out    (mf_x1_out),
    .mf_x2_out    (mf_x2_out)
);

// =============================================================================
// 7.  CLOCK GENERATOR   (only #-delay in the entire testbench)
// =============================================================================
initial clk = 1'b0;
always #CLK_HALF clk = ~clk;

// =============================================================================
// 8.  RESET DRIVER   (sole driver of rst_n — never driven by always block)
// =============================================================================
initial begin
    rst_n = 1'b0;
    repeat (RESET_CYCLES) @(posedge clk);
    @(negedge clk);       // De-assert on falling edge to avoid setup-time races
    rst_n = 1'b1;
end

// =============================================================================
// 9.  TEST-VECTOR LOADER   (completes at t=0, before any clocked event)
// =============================================================================
initial begin
    $display("------------------------------------------------------------");
    $display("[TB] Loading test vectors ...");
    $readmemh("rf_input.mem",  rf_input);
    $readmemh("ref_env22.mem", ref_env22);
    $readmemh("ref_env23.mem", ref_env23);
    $display("[TB]   rf_input  : %0d words  (Q2.30, sample-major)", RF_WORDS);
    $display("[TB]   ref_env22 : %0d pixels (Q2.30, ax-major)",     N_PIXELS);
    $display("[TB]   ref_env23 : %0d pixels (Q2.30, ax-major)",     N_PIXELS);
    $display("[TB]   Tolerance : %0d Q2.30 LSB", TOLERANCE);
    $display("------------------------------------------------------------");
end

// =============================================================================
// 10.  GLOBAL CYCLE COUNTER
// =============================================================================
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) cycle_cnt <= 32'd0;
    else        cycle_cnt <= cycle_cnt + 32'd1;
end

// =============================================================================
// 11.  WATCHDOG
// =============================================================================
always @(posedge clk) begin
    if (cycle_cnt == WATCHDOG_LIM[31:0]) begin
        $display("------------------------------------------------------------");
        $display("[TB] WATCHDOG TIMEOUT at cycle %0d", cycle_cnt);
        $display("[TB] tb_state=%0d  w1_lat=%b w2_lat=%b w3_lat=%b  busy=%b",
                  tb_state, w1_lat, w2_lat, w3_lat, pipeline_busy);
        $display("------------------------------------------------------------");
        $finish;
    end
end

// =============================================================================
// 12.  DONE-SIGNAL LATCHES
//   Each done signal from the DUT is a 1-cycle pulse.  These registers latch
//   the pulse so the polling FSM cannot miss it, even if the FSM takes more
//   than one cycle to reach the WAIT state.
//   Each latch is cleared in the same cycle the FSM transitions away from the
//   corresponding WAIT state (the set and clear are both in the same always
//   block but are in separate always blocks to avoid combinational priority
//   conflicts -- clear wins because the FSM transitions in the main block).
// =============================================================================
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        w1_lat <= 1'b0;
        w2_lat <= 1'b0;
        w3_lat <= 1'b0;
    end else begin
        // Set on rising edge of done pulse
        if (w1_done) w1_lat <= 1'b1;
        if (w2_done) w2_lat <= 1'b1;
        if (w3_done) w3_lat <= 1'b1;
        // Clear the moment the FSM consumes the latch
        if (tb_state == TB_WAIT_W1 && w1_lat) w1_lat <= 1'b0;
        if (tb_state == TB_WAIT_W2 && w2_lat) w2_lat <= 1'b0;
        if (tb_state == TB_WAIT_W3 && w3_lat) w3_lat <= 1'b0;
    end
end

// =============================================================================
// 13.  PROGRESS MONITOR  (one $display every ~5.2 M cycles while busy)
// =============================================================================
always @(posedge clk) begin
    if (pipeline_busy && (cycle_cnt[22:0] == 23'h0))
        $display("[TB] ... running  cycle=%0d  (~%0d ms)  state=%0d",
                  cycle_cnt, cycle_cnt / 100_000, tb_state);
end

// =============================================================================
// 14.  MAIN STIMULUS & CHECKING FSM
//   All DUT inputs are driven exclusively from this always block.
//   rst_n is READ here but NEVER ASSIGNED here (see block 8 above).
// =============================================================================
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        tb_state        <= TB_RESET;
        data_in         <= 8'h00;
        data_valid      <= 1'b0;
        start           <= 1'b0;
        out_rd_en       <= 1'b0;
        out_rd_addr     <= 17'h0;
        mf_rd_addr      <= 18'h0;
        word_idx        <= 18'h0;
        byte_sel        <= 2'd3;
        pix_rd          <= 17'h0;
        pix_chk         <= 17'h0;
        cap_env22       <= {DW{1'b0}};
        cap_env23       <= {DW{1'b0}};
        diff22          <= {DW{1'b0}};
        diff23          <= {DW{1'b0}};
        pass22          <= 32'd0;
        fail22          <= 32'd0;
        pass23          <= 32'd0;
        fail23          <= 32'd0;
        max_err22       <= {DW{1'b0}};
        max_err23       <= {DW{1'b0}};
        ff22_ax         <= 32'd0;
        ff22_lat        <= 32'd0;
        ff23_ax         <= 32'd0;
        ff23_lat        <= 32'd0;
        ff22_logged     <= 1'b0;
        ff23_logged     <= 1'b0;
        cyc_stream_start<= 32'd0;
        cyc_w1          <= 32'd0;
        cyc_w2          <= 32'd0;
        cyc_w3          <= 32'd0;
        post_rst_cnt    <= 5'd0;
        settle_cnt      <= 4'd0;
    end else begin

        // Default: deassert one-shot control signals every cycle
        start     <= 1'b0;
        out_rd_en <= 1'b0;

        case (tb_state)

            // ----------------------------------------------------------------
            // TB_RESET
            //   The negedge-reset above fires when rst_n goes low, resetting
            //   all registers.  When rst_n returns high the else-branch runs
            //   with tb_state == TB_RESET and we immediately move on.
            // ----------------------------------------------------------------
            TB_RESET: begin
                $display("[TB] Reset de-asserted at cycle %0d", cycle_cnt);
                post_rst_cnt <= 5'd0;
                tb_state     <= TB_POST_RST;
            end

            // ----------------------------------------------------------------
            // TB_POST_RST  -  brief idle so DUT internals stabilise
            // ----------------------------------------------------------------
            TB_POST_RST: begin
                post_rst_cnt <= post_rst_cnt + 5'd1;
                if (post_rst_cnt == POST_RST_CYC[4:0] - 5'd1)
                    tb_state <= TB_PULSE_START;
            end

            // ----------------------------------------------------------------
            // TB_PULSE_START
            //   Assert start=1 for exactly ONE cycle.
            //   W1 wrapper: S_IDLE detects start==1 and moves to S_LOAD_RF on
            //   the same posedge.  Byte streaming begins the very next cycle.
            //   Streaming state initialised here (word_idx=0, byte_sel=3).
            // ----------------------------------------------------------------
            TB_PULSE_START: begin
                start            <= 1'b1;
                data_valid       <= 1'b0;
                word_idx         <= 18'h0;
                byte_sel         <= 2'd3;
                cyc_stream_start <= cycle_cnt;
                tb_state         <= TB_STREAM;
                $display("[TB] START pulse at cycle %0d", cycle_cnt);
                $display("[TB] Streaming %0d bytes (%0d 32-bit words)",
                          RF_WORDS * 4, RF_WORDS);
            end

            // ----------------------------------------------------------------
            // TB_STREAM
            //   One byte per clock cycle, MSB first.  data_valid held high.
            //
            //   Memory layout that the W1 byte-assembler expects:
            //     word = rf_input[sample * NUM_CH + ch]
            //   Streaming order (row-major):
            //     sample 0: ch 0..127   then  sample 1: ch 0..127  ...
            //   Each word emitted as bytes: [31:24] [23:16] [15:8] [7:0].
            //
            //   W1 assembler logic (w1_matched_filter_wrapper.v):
            //     byte_idx 0..3, assembles MSB-first into word_buf,
            //     asserts word_valid when byte_idx reaches 3.
            //   Our emission order matches this exactly.
            //
            //   Transition: when the LSB of the last word is emitted, drop
            //   data_valid and move to TB_WAIT_W1.
            // ----------------------------------------------------------------
            TB_STREAM: begin
                data_valid <= 1'b1;

                case (byte_sel)
                    2'd3: data_in <= rf_input[word_idx][31:24];
                    2'd2: data_in <= rf_input[word_idx][23:16];
                    2'd1: data_in <= rf_input[word_idx][15:8];
                    2'd0: data_in <= rf_input[word_idx][7:0];
                    default: data_in <= 8'h00;
                endcase

                if (byte_sel == 2'd0) begin
                    // LSB of current word just emitted
                    if (word_idx == RF_WORDS[17:0] - 18'd1) begin
                        // Last byte of last word
                        data_valid <= 1'b0;
                        data_in    <= 8'h00;
                        tb_state   <= TB_WAIT_W1;
                        $display("[TB] Stream finished at cycle %0d  (%0d cyc for load)",
                                  cycle_cnt,
                                  cycle_cnt - cyc_stream_start);
                    end else begin
                        word_idx <= word_idx + 18'd1;
                        byte_sel <= 2'd3;
                    end
                end else begin
                    byte_sel <= byte_sel - 2'd1;
                end
            end

            // ----------------------------------------------------------------
            // TB_WAIT_W1  -  poll w1_lat (matched filtering complete)
            // ----------------------------------------------------------------
            TB_WAIT_W1: begin
                data_valid <= 1'b0;
                if (w1_lat) begin
                    cyc_w1   <= cycle_cnt;
                    tb_state <= TB_WAIT_W2;
                    $display("[TB] W1 done (Matched Filter) at cycle %0d  (+%0d cyc)",
                              cycle_cnt,
                              cycle_cnt - cyc_stream_start);
                end
            end

            // ----------------------------------------------------------------
            // TB_WAIT_W2  -  poll w2_lat (beamforming complete)
            // ----------------------------------------------------------------
            TB_WAIT_W2: begin
                if (w2_lat) begin
                    cyc_w2   <= cycle_cnt;
                    tb_state <= TB_WAIT_W3;
                    $display("[TB] W2 done (Beamforming) at cycle %0d  (+%0d cyc for BF)",
                              cycle_cnt,
                              cycle_cnt - cyc_w1);
                end
            end

            // ----------------------------------------------------------------
            // TB_WAIT_W3  -  poll w3_lat (Volterra filtering complete)
            // ----------------------------------------------------------------
            TB_WAIT_W3: begin
                if (w3_lat) begin
                    cyc_w3     <= cycle_cnt;
                    settle_cnt <= 4'd0;
                    tb_state   <= TB_SETTLE;
                    $display("[TB] W3 done (Volterra) at cycle %0d  (+%0d cyc for V)",
                              cycle_cnt,
                              cycle_cnt - cyc_w2);
                end
            end

            // ----------------------------------------------------------------
            // TB_SETTLE
            //   Allow SETTLE_CYC cycles so any remaining BRAM write-through
            //   effects complete before the readback loop begins.
            // ----------------------------------------------------------------
            TB_SETTLE: begin
                settle_cnt <= settle_cnt + 4'd1;
                if (settle_cnt == SETTLE_CYC[3:0] - 4'd1) begin
                    pix_rd   <= 17'h0;
                    tb_state <= TB_ADDR_PIX;
                    $display("[TB] Readback starting — checking %0d pixels", N_PIXELS);
                end
            end

            // ----------------------------------------------------------------
            // TB_ADDR_PIX
            //   Drive out_rd_addr with pix_rd.
            //   env22/env23 BRAMs in w3_volterra_wrapper use `assign` (comb
            //   read in behavioural sim).  We still insert one pipeline stage
            //   so the testbench correctly mirrors post-synthesis behaviour
            //   where block-RAMs have 1-cycle registered read latency.
            // ----------------------------------------------------------------
            TB_ADDR_PIX: begin
                out_rd_en   <= 1'b1;
                out_rd_addr <= pix_rd;
                tb_state    <= TB_SAMPLE_PIX;
            end

            // ----------------------------------------------------------------
            // TB_SAMPLE_PIX
            //   One cycle after driving the address, latch the output values.
            //   Also save the address being checked and advance pix_rd.
            // ----------------------------------------------------------------
            TB_SAMPLE_PIX: begin
                cap_env22 <= env22_out;
                cap_env23 <= env23_out;
                pix_chk   <= pix_rd;
                pix_rd    <= pix_rd + 17'h1;
                tb_state  <= TB_CHECK_PIX;
            end

            // ----------------------------------------------------------------
            // TB_CHECK_PIX
            //   Compute unsigned absolute difference for each output.
            //   env22/env23 are non-negative envelopes stored as unsigned Q2.30
            //   in both the DUT BRAMs and the reference files, so plain
            //   unsigned subtraction is correct for the difference.
            //
            //   ax  = pix_chk / NUM_LAT  = pix_chk[16:7]   (NUM_LAT = 128 = 2^7)
            //   lat = pix_chk % NUM_LAT  = pix_chk[6:0]
            // ----------------------------------------------------------------
            TB_CHECK_PIX: begin

                // --- env22 ---
                diff22 = (cap_env22 >= ref_env22[pix_chk])
                       ? (cap_env22 - ref_env22[pix_chk])
                       : (ref_env22[pix_chk] - cap_env22);

                if (diff22 <= TOLERANCE) begin
                    pass22 <= pass22 + 32'd1;
                end else begin
                    fail22 <= fail22 + 32'd1;
                    if (!ff22_logged) begin
                        ff22_logged <= 1'b1;
                        ff22_ax     <= {22'h0, pix_chk[16:7]};  // 10-bit / 128
                        ff22_lat    <= {25'h0, pix_chk[6:0]};   //  7-bit % 128
                        $display("[FAIL env22] ax=%0d lat=%0d  exp=0x%08X  got=0x%08X  diff=%0d",
                                  pix_chk[16:7], pix_chk[6:0],
                                  ref_env22[pix_chk], cap_env22, diff22);
                    end
                end
                if (diff22 > max_err22) max_err22 <= diff22;

                // --- env23 ---
                diff23 = (cap_env23 >= ref_env23[pix_chk])
                       ? (cap_env23 - ref_env23[pix_chk])
                       : (ref_env23[pix_chk] - cap_env23);

                if (diff23 <= TOLERANCE) begin
                    pass23 <= pass23 + 32'd1;
                end else begin
                    fail23 <= fail23 + 32'd1;
                    if (!ff23_logged) begin
                        ff23_logged <= 1'b1;
                        ff23_ax     <= {22'h0, pix_chk[16:7]};
                        ff23_lat    <= {25'h0, pix_chk[6:0]};
                        $display("[FAIL env23] ax=%0d lat=%0d  exp=0x%08X  got=0x%08X  diff=%0d",
                                  pix_chk[16:7], pix_chk[6:0],
                                  ref_env23[pix_chk], cap_env23, diff23);
                    end
                end
                if (diff23 > max_err23) max_err23 <= diff23;

                // Advance or finish
                if (pix_chk == N_PIXELS[16:0] - 17'h1)
                    tb_state <= TB_REPORT;
                else
                    tb_state <= TB_ADDR_PIX;
            end

            // ----------------------------------------------------------------
            // TB_REPORT
            // ----------------------------------------------------------------
            TB_REPORT: begin
                $display("============================================================");
                $display("[TB]  TIMING  SUMMARY");
                $display("       Streaming started : cycle %0d", cyc_stream_start);
                $display("       W1 done (MF)      : cycle %0d  (+%0d cycles)",
                          cyc_w1, cyc_w1 - cyc_stream_start);
                $display("       W2 done (BF)      : cycle %0d  (+%0d cycles)",
                          cyc_w2, cyc_w2 - cyc_w1);
                $display("       W3 done (Volterra) : cycle %0d  (+%0d cycles)",
                          cyc_w3, cyc_w3 - cyc_w2);
                $display("       Total pipeline    : %0d cycles  (~%0d ms @ 100 MHz)",
                          cyc_w3 - cyc_stream_start,
                          (cyc_w3 - cyc_stream_start) / 100_000);
                $display("------------------------------------------------------------");
                $display("[TB]  RESULT SUMMARY  (tolerance %0d LSB)", TOLERANCE);
                $display("       env22  PASS=%0d  FAIL=%0d  max_err=%0d LSB",
                          pass22, fail22, max_err22);
                $display("       env23  PASS=%0d  FAIL=%0d  max_err=%0d LSB",
                          pass23, fail23, max_err23);
                if (fail22 != 32'd0)
                    $display("       First env22 fail : ax=%0d lat=%0d",
                              ff22_ax, ff22_lat);
                if (fail23 != 32'd0)
                    $display("       First env23 fail : ax=%0d lat=%0d",
                              ff23_ax, ff23_lat);
                $display("------------------------------------------------------------");
                if (fail22 == 32'd0 && fail23 == 32'd0)
                    $display("[TB]  *** ALL %0d PIXELS PASSED ***", N_PIXELS);
                else
                    $display("[TB]  *** FAILED: %0d env22 + %0d env23 mismatches ***",
                              fail22, fail23);
                $display("============================================================");
                tb_state <= TB_DONE;
            end

            // ----------------------------------------------------------------
            // TB_DONE  -  simulation ends
            // ----------------------------------------------------------------
            TB_DONE: begin
                $finish;
            end

            default: tb_state <= TB_RESET;

        endcase
    end
end

endmodule


// =============================================================================
// =============================================================================
//
//  MATLAB SCRIPT  gen_tb_vectors.m
//  ---------------------------------
//  Call AFTER running volterra_code_with_custom.m so all workspace variables
//  (RData, Trans, Receive, H_par_scaled, reborn) are available.
//
//  Usage from the MATLAB command window:
//      gen_tb_vectors(RData, Trans, Receive, H_par_scaled, reborn)
//
//  Outputs (written to current MATLAB working directory):
//      rf_input.mem    229376 lines of 8 hex chars  (Q2.30 RF data, sample-major)
//      ref_env22.mem   124544 lines of 8 hex chars  (Q2.30 expected quad env)
//      ref_env23.mem   124544 lines of 8 hex chars  (Q2.30 expected cubic env)
//
//  Fixed-point encoding used throughout (must match FPGA RTL exactly):
//      Q2.30 signed 32-bit:
//        raw_int   = int32(round(value * 2^30))
//        hex_str   = dec2hex(typecast(raw_int, 'uint32'), 8)
//
//  The pipeline is re-run in MATLAB with the same intermediate quantisation
//  steps as the RTL so that the reference values are as close as possible to
//  the actual FPGA output.  The 5000-LSB testbench tolerance covers any
//  residual discrepancy from CORDIC / adder rounding in the beamformer.
//
// =============================================================================
//
// function gen_tb_vectors(RData, Trans, Receive, H_par_scaled, reborn)
// fprintf('=== gen_tb_vectors: generating FPGA testbench .mem files ===\n');
//
// %% ---- Constants ----------------------------------------------------------
// Q30    = 2^30;
// c      = 1540;
// tFs    = 250e6;
// w2mm   = 1e-3 * c / Trans.frequency;
// NUM_CH = 128;
// L_SAMP = Receive(1).endSample;        % 1792
// M      = reborn.m;                    % 15
//
// %% Recompute Fs using identical rounding logic as the main script ----------
// Fs = 4 * Trans.frequency;             % MHz
// kk = 250 / Fs;
// [~,ii] = min([Fs - 250/ceil(kk), 250/floor(kk) - Fs]);
// Fs = ((2-ii)*250/ceil(kk) + (ii-1)*250/floor(kk));
// ts_c = (1e-3 / Fs) * c;              % Spatial sampling step (mm per sample)
//
// to_h32 = @(v) dec2hex(typecast(int32(round(v)), 'uint32'), 8);
//
// fprintf('  Fs=%.4f MHz   ts_c=%.6f mm   L_SAMP=%d   M=%d\n', ...
//          Fs, ts_c, L_SAMP, M);
//
// %% ---- STEP 1: rf_input.mem  (normalized RF data) ------------------------
// fprintf('Step 1: Building rf_input.mem (%d words) ...\n', L_SAMP * NUM_CH);
//
// x_raw       = double(RData(1:L_SAMP, :, 1));     % L_SAMP x 128
// norm_factor = max(abs(x_raw(:)));
// x_norm      = x_raw / norm_factor;               % values in (-1, 1]
//
// % Clamp to Q2.30 representable range before quantising
// x_norm = max(-1.0, min(1.0 - 2^-30, x_norm));
//
// % Quantise to Q2.30 (this is exactly what the FPGA stores internally)
// x_norm_q = round(x_norm * Q30) / Q30;
//
// fid = fopen('rf_input.mem', 'w');
// if fid < 0, error('Cannot create rf_input.mem'); end
// % Sample-major order: for sample s (1-based), write all 128 channels
// for s = 1 : L_SAMP
//     for ch = 1 : NUM_CH
//         fprintf(fid, '%s\n', to_h32(x_norm_q(s, ch) * Q30));
//     end
// end
// fclose(fid);
// fprintf('  rf_input.mem written (%d lines).\n', L_SAMP * NUM_CH);
//
// %% ---- STEP 2: Chirp templates -------------------------------------------
// adr = 'C:\Users\DELL\Downloads\';
// y1  = load([adr 'chi7to12cycle16bw100.mat']);
// y2  = load([adr 'chi3pt5to6cycle8bw100.mat']);
// tw1 = y1.TW.Waveform;  tw2 = y2.TW.Waveform;
//
// t1 = (1:length(tw1)) / tFs;
// t1n = (1/(Fs*1e6)) : (1/(Fs*1e6)) : (length(tw1)/tFs);
// ww1 = interp1(t1, tw1, t1n, 'linear', 0)';
// ww1 = ww1 / max(abs(ww1));
// FW1 = [zeros(length(ww1), 1); ww1];   % 136 x 1
//
// t2 = (1:length(tw2)) / tFs;
// t2n = (1/(Fs*1e6)) : (1/(Fs*1e6)) : (length(tw2)/tFs);
// ww2 = interp1(t2, tw2, t2n, 'linear', 0)';
// ww2 = ww2 / max(abs(ww2));
// FW2 = [zeros(length(ww2), 1); ww2];   % 136 x 1
//
// % Quantise taps (identical encoding to fw1/fw2_coeffs.mem)
// FW1_q = round(FW1 * Q30) / Q30;
// FW2_q = round(FW2 * Q30) / Q30;
//
// %% ---- STEP 3: Quantised matched filtering --------------------------------
// fprintf('Step 3: Matched filtering ...\n');
// x2_mf = zeros(L_SAMP, NUM_CH);
// for ch = 1 : NUM_CH
//     tmp = conv(x_norm_q(:, ch), FW2_q);     % Full linear convolution
//     % Take causal portion (first L_SAMP samples, matching FIR pipeline)
//     tmp_q = round(tmp(1:L_SAMP) * Q30) / Q30;
//     x2_mf(:, ch) = tmp_q;
// end
// fprintf('  Matched filtering done.\n');
//
// %% ---- STEP 4: Quantised beamforming -------------------------------------
// start_depth = Receive(1).startDepth * w2mm;
// end_depth   = Receive(1).endDepth   * w2mm;
// ddz         = (end_depth - start_depth) / (L_SAMP - 1);
// hh          = start_depth : ddz : 26;            % 1 x 973 axial grid (mm)
// ex          = Trans.ElementPos(:, 1) * w2mm;     % 128 x 1 element positions
// ww          = ex';                               % 1 x 128 lateral positions
// Neighbor    = 25;
// NUM_AXIAL   = length(hh);
//
// fprintf('Step 4: Beamforming (%d x %d pixels) ...\n', NUM_AXIAL, NUM_CH);
// x2_bf = zeros(NUM_AXIAL, NUM_CH);
// for lat = 1 : NUM_CH
//     x_pix = ww(lat);
//     for ax = 1 : NUM_AXIAL
//         z_pix    = hh(ax);
//         el_start = max(1, lat - Neighbor);
//         el_end   = min(NUM_CH, lat + Neighbor);
//         n_el     = el_end - el_start + 1;
//         psum     = 0.0;
//         for el = el_start : el_end
//             dist = sqrt((ex(el) - x_pix)^2 + z_pix^2);
//             k_n  = round((z_pix + dist - 2*start_depth) / ts_c + 1);
//             k_n  = max(1, min(L_SAMP, k_n));
//             psum = psum + x2_mf(k_n, el);
//         end
//         x2_bf(ax, lat) = round((psum / n_el) * Q30) / Q30;
//     end
//     if mod(lat, 16) == 0
//         fprintf('  ... lateral %3d / %d\n', lat, NUM_CH);
//     end
// end
// fprintf('  Beamforming done.\n');
//
// %% ---- STEP 5: Quantised Volterra filter ---------------------------------
// fprintf('Step 5: Volterra filter (%d x %d valid pixels) ...\n', ...
//          NUM_AXIAL - M, NUM_CH);
//
// d   = reborn.d;
// hw  = reborn.hw;
// h2  = H_par_scaled.h2;
// h3  = H_par_scaled.h3;
//
// % Quantise kernels and apply pre-weights (mirrors V_out: h2 = h2 .* hw{2})
// h2_q = round(h2 .* hw{2} * Q30) / Q30;
// h3_q = round(h3 .* hw{3} * Q30) / Q30;
//
// env22_ref = zeros(NUM_AXIAL, NUM_CH);
// env23_ref = zeros(NUM_AXIAL, NUM_CH);
//
// for ax = M : NUM_AXIAL
//     window = flipud(x2_bf(ax - M + 1 : ax, :));   % M x NUM_CH (flipud)
//     for lat = 1 : NUM_CH
//         yy = window(:, lat);                       % M x 1
//
//         % Quadratic: 120 pair-products, Q4.60 intermediate
//         p2   = prod(yy(d{2}), 2);
//         p2_q = round(p2 * Q30^2) / Q30^2;         % Quantise products
//         z2   = p2_q' * h2_q;                      % Dot product
//
//         % Cubic: 680 triple-products, Q6.90 intermediate
//         p3   = prod(yy(d{3}), 2);
//         p3_q = round(p3 * Q30^3) / Q30^3;
//         z3   = p3_q' * h3_q;
//
//         env22_ref(ax, lat) = abs(z2);
//         env23_ref(ax, lat) = abs(z3);
//     end
//     if mod(ax, 100) == 0
//         fprintf('  ... axial %4d / %d\n', ax, NUM_AXIAL);
//     end
// end
// fprintf('  Volterra filter done.\n');
//
// %% ---- STEP 6: Write ref_env22.mem ---------------------------------------
// fprintf('Step 6: Writing ref_env22.mem (%d pixels) ...\n', NUM_AXIAL * NUM_CH);
// env22_ref = max(0, min(env22_ref, 2 - 2^-30));
// fid = fopen('ref_env22.mem', 'w');
// if fid < 0, error('Cannot create ref_env22.mem'); end
// for ax = 1 : NUM_AXIAL
//     for lat = 1 : NUM_CH
//         fprintf(fid, '%s\n', to_h32(env22_ref(ax, lat) * Q30));
//     end
// end
// fclose(fid);
// fprintf('  ref_env22.mem written.\n');
//
// %% ---- STEP 7: Write ref_env23.mem ---------------------------------------
// fprintf('Step 7: Writing ref_env23.mem (%d pixels) ...\n', NUM_AXIAL * NUM_CH);
// env23_ref = max(0, min(env23_ref, 2 - 2^-30));
// fid = fopen('ref_env23.mem', 'w');
// if fid < 0, error('Cannot create ref_env23.mem'); end
// for ax = 1 : NUM_AXIAL
//     for lat = 1 : NUM_CH
//         fprintf(fid, '%s\n', to_h32(env23_ref(ax, lat) * Q30));
//     end
// end
// fclose(fid);
// fprintf('  ref_env23.mem written.\n');
//
// %% ---- STEP 8: Summary ----------------------------------------------------
// fprintf('\n=== Statistics ===\n');
// fprintf('  env22  min=%+.3e  max=%.3e  mean=%.3e  nnz=%d/%d\n', ...
//   min(env22_ref(:)), max(env22_ref(:)), mean(env22_ref(:)), ...
//   sum(env22_ref(:)>0), NUM_AXIAL*NUM_CH);
// fprintf('  env23  min=%+.3e  max=%.3e  mean=%.3e  nnz=%d/%d\n', ...
//   min(env23_ref(:)), max(env23_ref(:)), mean(env23_ref(:)), ...
//   sum(env23_ref(:)>0), NUM_AXIAL*NUM_CH);
// fprintf('\nCopy rf_input.mem, ref_env22.mem, ref_env23.mem\n');
// fprintf('to your Vivado project simulation sources directory.\n');
// fprintf('=== gen_tb_vectors complete ===\n');
//
// end  % function gen_tb_vectors
//
// =============================================================================
// END gen_tb_vectors.m
// =============================================================================
